
graph TD
    subgraph Legend
        Z1[Todo]:::todo
        Z2[In Progress]:::inProgress
        Z3[Done]:::done
        Z4[Directory]:::directory
    end
    subgraph Project Structure
    subgraph PD[Project Description]
        My-4th-Project:::done
        Write A Python Script To Plot Something And Make A Report Using The Jpg File Created:::done
        PJSTATUS[IN-PROGRESS]:::inProgress %% TODO|IN-PROGRESS|DONE
    end
    subgraph PDIR[Project Directory]
        Root["/home/ywatanabe/proj/llemacs/workspace/projects/033-my-4th-project"]:::directory
        Config[config/]:::directory
        Data[data/]:::directory
        Scripts[scripts/]:::directory
        Results[results/]:::directory
        Resources[resources/]:::directory
        Env[.env/]:::directory
        Git[.git/]:::directory
        Requirements[requirements.txt/]:::directory
        Log[Log.txt/]:::directory
        PM[project_management.mmd]:::directory
    end
    end
    subgraph Execution Flow
    subgraph Step
        D[Compile Context]:::done
        E[Generate Elisp]:::inProgress
        F[Execute Elisp]:::todo
        G{Success?}:::todo
    end
    subgraph "Logging, Version Control, and State Update"
        H[Log Success]:::todo
        I[Log Error]:::todo
        J{Milestone?}:::todo
        K[Git Commit]:::todo
        L[Log Only]:::todo
        M{Goal Met?}:::todo
        N[Update Project_States]:::todo
    end
    end
    subgraph PMFLOW[Project Management Flow]
        MS1[Milestone 1]:::done
        MS2[Milestone 2]:::inProgress
    subgraph Tasks M1
        T1[task1]:::done
        T2[task2]:::done
    end
    subgraph Tasks M2
        T3[task1]:::done
        T4[task2]:::todo
    end
    end
    Start[Start]:::starttag --> PD
    PD --> PDIR
    PM --> PMFLOW
    PMFLOW --> PM
    PDIR --> D
    D --> E --> F --> G
    G -- Yes --> H
    G -- No --> I
    H --> J
    J -- Yes --> K
    J -- No --> L
    K --> M
    I --> L
    L --> M
    M -- No --> N
    N --> Root
    M -- Yes --> End[End]:::endtag
    PJGOALS --> PMFLOW
    MS1 --> T1
    MS1 --> T2
    MS2 --> T3
    MS2 --> T4
    classDef starttag fill:#cce5ff,stroke:#333,stroke-width:2px;
    classDef done fill:#9f9,stroke:#333,stroke-width:2px;
    classDef inProgress fill:#ff9,stroke:#333,stroke-width:2px;
    classDef todo fill:#fff,stroke:#333,stroke-width:2px;
    classDef directory fill:#efe,stroke:#333,stroke-width:1px;
    classDef endtag fill:#fcc,stroke:#333,stroke-width:2px;
    class Root,Config,Data,Scripts,Results,Resources directory;