#!/bin/bash
setup_workspace() {
    local workspace_dir="/workspace"
    local timestamp=$(date +%Y-%m-%d-%H-%M-%S)
    local project_id="001"
    local ninja_id="001"
    local user1="USER1"
    local user2="USER2"

    # Create directories
    mkdir -p "$workspace_dir/ninjas/ninja-$ninja_id/memory/projects/$project_id"
    mkdir -p "$workspace_dir/ninjas/ninja-$ninja_id/messages/inbox"
    mkdir -p "$workspace_dir/ninjas/ninja-$ninja_id/messages/outbox"
    mkdir -p "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/messages/inbox"
    mkdir -p "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/messages/outbox"
    mkdir -p "$workspace_dir/projects/project-$project_id/data"
    mkdir -p "$workspace_dir/projects/project-$project_id/docs"
    mkdir -p "$workspace_dir/projects/project-$project_id/outputs/report-001"
    mkdir -p "$workspace_dir/projects/project-$project_id/issues"
    mkdir -p "$workspace_dir/shared/agents/templates"
    mkdir -p "$workspace_dir/shared/agents/configs"
    mkdir -p "$workspace_dir/shared/system/logs"
    mkdir -p "$workspace_dir/shared/prompts"
    mkdir -p "$workspace_dir/shared/tools/tool-001"
    mkdir -p "$workspace_dir/shared/knowledge_base"


    # Create files
    touch "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/messages/inbox/README.md"
    touch "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/messages/outbox/README.md"
    touch "$workspace_dir/ninjas/ninja-$ninja_id/messages/README.md"
    touch "$workspace_dir/ninjas/ninja-$ninja_id/messages/inbox/README.md"
    touch "$workspace_dir/ninjas/ninja-$ninja_id/messages/outbox/README.md"
    touch "$workspace_dir/ninjas/ninja-$ninja_id/memory/README.md"
    touch "$workspace_dir/projects/project-$project_id/scripts/README.md"
    touch "$workspace_dir/ninjas/ninja-$ninja_id/README.md"


    # Create symlink
    ln -s "$workspace_dir/projects/project-$project_id/data" "$workspace_dir/projects/project-$project_id/outputs/report-001/data"

    # Create Templates
    create_agent_template "$workspace_dir"
    create_agent_config "$workspace_dir"
    create_system_log_template "$workspace_dir"
    create_tool_md_template "$workspace_dir"
    create_prompt_template "$workspace_dir"
    create_knowledge_base_template "$workspace_dir"
    create_data_readme_template "$workspace_dir"
    create_docs_readme_template "$workspace_dir"
    create_report_readme_template "$workspace_dir"
    create_outputs_readme_template "$workspace_dir"
    create_issue_template "$workspace_dir" "$timestamp"
    create_project_readme_template "$workspace_dir"
    create_projects_readme_template "$workspace_dir"
    create_ninja_project_readme_template "$workspace_dir"
    create_memory_template "$workspace_dir" "$timestamp"
    create_message_json_template "$workspace_dir" "$user1" "$user2"
    create_status_template "$workspace_dir" "$project_id" "$timestamp"
    create_tasks_json_template "$workspace_dir" "$project_id"
    create_forum_template "$workspace_dir" "$project_id"
    create_profile_template "$workspace_dir"
    create_tool_json_template "$workspace_dir"
    create_tool_schema_template "$workspace_dir"
    create_prompt_json_template "$workspace_dir"
    create_memory_json_template "$workspace_dir" "$timestamp"
    create_forum_json_template "$workspace_dir" "$project_id"
    create_profile_json_template "$workspace_dir"

    # Create md to json

    md2json_agent_template "$workspace_dir/shared/agents/templates/agent-template.md"
    md2json_agent_config "$workspace_dir/shared/agents/configs/.agent-config.md"
    md2json_tool_template "$workspace_dir/shared/tools/tool-001/tool.md"
    md2json_prompt_template "$workspace_dir/shared/prompts/prompt-template.md"
    md2json_knowledge_base_template "$workspace_dir/shared/knowledge_base/.knowledge.md"
    md2json_data_readme_template "$workspace_dir/projects/project-$project_id/data/README.md"
    md2json_docs_readme_template "$workspace_dir/projects/project-$project_id/docs/README.md"
    md2json_report_readme_template "$workspace_dir/projects/project-$project_id/outputs/report-001/README.md"
    md2json_outputs_readme_template "$workspace_dir/projects/project-$project_id/outputs/README.md"
    md2json_issue_template "$workspace_dir/projects/project-$project_id/issues/$timestamp-TITLE-001.md"
    md2json_project_readme_template "$workspace_dir/projects/project-$project_id/README.md"
    md2json_projects_readme_template "$workspace_dir/projects/README.md"
    md2json_ninja_project_readme_template "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/README.md"
    md2json_memory_template "$workspace_dir/ninjas/ninja-$ninja_id/memory/projects/$project_id/$timestamp-TITLE.md"
    md2json_status_template "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/status.md"
    md2json_forum_template "$workspace_dir/projects/project-$project_id/forum.md"
    md2json_profile_template "$workspace_dir/ninjas/ninja-$ninja_id/profile.md"

    #verify json and md
    verify_json_agent_template "$workspace_dir/shared/agents/templates/agent-template.json"
    verify_md_agent_template "$workspace_dir/shared/agents/templates/agent-template.md"
    verify_json_agent_config "$workspace_dir/shared/agents/configs/.agent-config.json"
    verify_md_agent_config "$workspace_dir/shared/agents/configs/.agent-config.md"
    verify_json_tool_template "$workspace_dir/shared/tools/.tool-001.json"
    verify_md_tool_template "$workspace_dir/shared/tools/tool-001/tool.md"
    verify_json_prompt_template "$workspace_dir/shared/prompts/.prompt-template.json"
    verify_md_prompt_template "$workspace_dir/shared/prompts/prompt-template.md"
    verify_json_knowledge_base_template "$workspace_dir/shared/knowledge_base/.knowledge.json"
    verify_md_knowledge_base_template "$workspace_dir/shared/knowledge_base/.knowledge.md"
    verify_json_data_readme_template "$workspace_dir/projects/project-$project_id/data/.README.json"
    verify_md_data_readme_template "$workspace_dir/projects/project-$project_id/data/README.md"
    verify_json_docs_readme_template "$workspace_dir/projects/project-$project_id/docs/.README.json"
    verify_md_docs_readme_template "$workspace_dir/projects/project-$project_id/docs/README.md"
    verify_json_report_readme_template "$workspace_dir/projects/project-$project_id/outputs/report-001/.README.json"
    verify_md_report_readme_template "$workspace_dir/projects/project-$project_id/outputs/report-001/README.md"
    verify_json_outputs_readme_template "$workspace_dir/projects/project-$project_id/outputs/.README.json"
    verify_md_outputs_readme_template "$workspace_dir/projects/project-$project_id/outputs/README.md"
    verify_json_issue_template "$workspace_dir/projects/project-$project_id/issues/$timestamp-TITLE-001.json"
    verify_md_issue_template "$workspace_dir/projects/project-$project_id/issues/$timestamp-TITLE-001.md"
    verify_json_project_readme_template "$workspace_dir/projects/project-$project_id/.README.json"
    verify_md_project_readme_template "$workspace_dir/projects/project-$project_id/README.md"
    verify_json_projects_readme_template "$workspace_dir/projects/.README.json"
    verify_md_projects_readme_template "$workspace_dir/projects/README.md"
    verify_json_ninja_project_readme_template "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/.README.json"
    verify_md_ninja_project_readme_template "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/README.md"
    verify_json_memory_template "$workspace_dir/ninjas/ninja-$ninja_id/memory/projects/$project_id/$timestamp-TITLE.json"
    verify_md_memory_template "$workspace_dir/ninjas/ninja-$ninja_id/memory/projects/$project_id/$timestamp-TITLE.md"
    verify_json_status_template "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/.status.json"
    verify_md_status_template "$workspace_dir/ninjas/ninja-$ninja_id/projects/project-$project_id/status.md"
    verify_json_forum_template "$workspace_dir/projects/project-$project_id/.forum.json"
    verify_md_forum_template "$workspace_dir/projects/project-$project_id/forum.md"
    verify_json_profile_template "$workspace_dir/ninjas/ninja-$ninja_id/.profile.json"
    verify_md_profile_template "$workspace_dir/ninjas/ninja-$ninja_id/profile.md"

    # Create dummy data file
    echo "This is a dummy dataset." > "$workspace_dir/projects/project-$project_id/data/dataset.txt"
    echo "This is a dummy report." > "$workspace_dir/projects/project-$project_id/outputs/report-001/report.pdf"


    echo ""
    echo "========================================"
    echo "Workspace setup complete in $workspace_dir"
    echo "========================================"
    echo ""
    tree "$workspace_dir/ninjas"
    echo ""
    tree "$workspace_dir/projects"
    echo ""
    tree "$workspace_dir/shared"
    echo ""
}
